
name: NixOS 
  
on: [push] 
  
jobs: 
  build: 
    runs-on: ubuntu-18.04 
    steps: 
      - uses: actions/checkout@v2.3.2 
  
      - name: "Install Nix ❄️" 
        uses: cachix/install-nix-action@v15 
  
      - name: "Install Cachix ❄️" 
        uses: cachix/cachix-action@v10 
        with: 
          name: damaen
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}" 
  
      - name: "Build NixOS config ❄️" 
        run: ./build ci-system
